export enum SupportUkraineSections {
  AboutZapal = 'AboutZapal',
  HumanitarianRelief = 'HumanitarianRelief',
  UkrainianOrganizations = 'UkrainianOrganizations',
  NationalBankOfUkraine = 'NationalBankOfUkraine',
  NgoComeBackAlive = 'NgoComeBackAlive',
  SerhiyPritula = 'SerhiyPritula',
  ArmySos = 'ArmySos',
  Hospitallers = 'Hospitallers',
  VoicesOfChildren = 'VoicesOfChildren',
  UkraineCrisisMediaCenter = 'UkraineCrisisMediaCenter',
  ForeignCharityOrganisations = 'ForeignCharityOrganisations',
  HelpUsHelp = 'HelpUsHelp',
  WithUkraine = 'WithUkraine',
  LelekaFoundation = 'LelekaFoundation',
  ReadAndShareCredibleInformation = 'ReadAndShareCredibleInformation',
  ProtestPeacefully = 'ProtestPeacefully',
  BanRussianBusinesses = 'BanRussianBusinesses',
  SupportUkrainianBusinesses = 'SupportUkrainianBusinesses',
  HelpRefugees = 'HelpRefugees',
  Conclusion = 'Conclusion',
}
