#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^([A-Z]{3}-[0-9]{1,5}\s){0,5}(feat|fix|docs|style|refactor|test|merge|chore)(\(.{1,10}\))?!?:\s.{1,}"

if ! (echo "$message" | grep -Pq $requiredPattern);
then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "-"
  echo "The commit message must have this format:"
  echo "KEY-123 feat(scope)!: add hat wobble..."
  echo "^-----^ ^--^ ^----^^  ^------------^"
  echo "|       |    |     |  |"
  echo "|       |    |     |  +-> Summary in present tense."
  echo "|       |    |     |"
  echo "|       |    |     +----> Optional '!' to draw attention to breaking change"
  echo "|       |    |"
  echo "|       |    +----------> Optional scope(1-10 chars); e.g. api, front, ci, cd, etc."
  echo "|       |"
  echo "|       +---------------> Type"
  echo "|"
  echo "+-----------------------> Optional issue key in Jira (UPPERCASE; Smart Commits)"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
